export const APP_NAME = process.env.NEXT_PUBLIC_APP_NAME || "Ecommrece Next";

export const APP_NAME_DESCRIPTION =
  process.env.NEXT_PUBLIC_APP_NAME_DESCRIPTION || "Generated by Abdul Rehman";

export const SERVICE_URL =
  process.env.NEXT_PUBLIC_SERVICE_URL || "http://localhost:3000/";
